//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MyLanguageGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MyLanguageGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMyLanguageGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] MyLanguageGrammarParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] MyLanguageGrammarParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.moduleStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleStatements([NotNull] MyLanguageGrammarParser.ModuleStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.variablesDeclarationBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariablesDeclarationBlock([NotNull] MyLanguageGrammarParser.VariablesDeclarationBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.variablesDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariablesDeclaration([NotNull] MyLanguageGrammarParser.VariablesDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] MyLanguageGrammarParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure([NotNull] MyLanguageGrammarParser.ProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDeclaration([NotNull] MyLanguageGrammarParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.procedureParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureParameters([NotNull] MyLanguageGrammarParser.ProcedureParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.procedureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureBody([NotNull] MyLanguageGrammarParser.ProcedureBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MyLanguageGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureCall([NotNull] MyLanguageGrammarParser.ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MyLanguageGrammarParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpression([NotNull] MyLanguageGrammarParser.SimpleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOperator([NotNull] MyLanguageGrammarParser.AddOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] MyLanguageGrammarParser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] MyLanguageGrammarParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] MyLanguageGrammarParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] MyLanguageGrammarParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] MyLanguageGrammarParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] MyLanguageGrammarParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] MyLanguageGrammarParser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] MyLanguageGrammarParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] MyLanguageGrammarParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MyLanguageGrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] MyLanguageGrammarParser.ReturnStatementContext context);
}
